# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

os: linux
dist: trusty
sudo: false
language: python
cache: pip

python:
  - "3.5"
  - "3.7"

install: pip install tox-travis
script: tox
